fix -S -n/-p, update help

diff --git a/bin/multi_clipboard b/bin/multi_clipboard
--- a/bin/multi_clipboard
+++ b/bin/multi_clipboard
@@ -35,7 +35,10 @@ _s_help="
 Usage:
 
     $ multi_clipboard -i [args]
-    # Push [args]to the clipboard list
+    # Push [args] to the clipboard list
+
+    $ multi_clipboard -s [args]
+    # Send [args] to the clipboard list and the screen's clipboard
 
     $ multi_clipboard -I
     # Push the screen's clipboard to the clipboard list
@@ -46,12 +49,6 @@ Usage:
 
     $ multi_clipboard -O
     # Same as -o, in addition, send it to the screen's clipboard
-
-    $ multi_clipboard -s [args]
-    # Send [args] to the screen's clipboard
-
-    $ multi_clipboard -S
-    # Use in screen for selection mode.
 
     $ multi_clipboard -w # or w/o any other options
     # Launch selection window
@@ -66,6 +63,9 @@ Usage:
 
     $ multi_clipboard -c
     # Clean up clipboard file
+
+    $ multi_clipboard -S
+    # Use in screen for selection mode (for screen binding, not for command line, see below)
 
     $ multi_clipboard snippet [option]
     # Use 'snippet' file instead of saved clipboards.
@@ -373,10 +373,10 @@ function mcpoponsc_next { # {{{
   screen -X msgminwait 0
   mcpoponsc_n=$(cat $f_mcpoponsc_n)
   nclbs=$(cat $f_nclbs)
-  if [ "$mcpoponsc_n" -eq 0 ];then
-    mcpoponsc_n=$((nclbs-1))
+  if [ "$mcpoponsc_n" -eq $((nclbs-1)) ];then
+    mcpoponsc_n=0
   else
-    ((mcpoponsc_n--))
+    ((mcpoponsc_n++))
   fi
   echo $mcpoponsc_n > $f_mcpoponsc_n
   mcpoponsc_messaage
@@ -387,10 +387,10 @@ function mcpoponsc_prev { # {{{
   screen -X msgminwait 0
   mcpoponsc_n=$(cat $f_mcpoponsc_n)
   nclbs=$(cat $f_nclbs)
-  if [ "$mcpoponsc_n" -eq $((nclbs-1)) ];then
-    mcpoponsc_n=0
+  if [ "$mcpoponsc_n" -eq 0 ];then
+    mcpoponsc_n=$((nclbs-1))
   else
-    ((mcpoponsc_n++))
+    ((mcpoponsc_n--))
   fi
   echo $mcpoponsc_n > $f_mcpoponsc_n
   mcpoponsc_messaage
@@ -511,15 +511,43 @@ _sf_check_args () { # {{{
     _s_file=$snp
     shift
   fi
-  if [ "$1" = "-h" ];then
+  if [ "$1" = "-i" ];then
     shift
-    _sf_help
+    _sf_push "$*"
+    mccopy2cl "${_s_inputs[0]}"
   elif [ "$1" = "-s" ];then
-    # pushpopsc
     shift
     _sf_push "$*"
     mccopy2cl "${_s_inputs[0]}"
     mcpopsc
+  elif [ "$1" = "-I" ];then
+    shift
+    touch "$scex"
+    screen -X writebuf
+    _s_noshow=1
+    _sf_push "$(cat "$scex")"
+    mccopy2cl "$(cat "$scex")"
+  elif [ "$1" = "-o" ];then
+    # pop
+    shift
+    mcpop
+  elif [ "$1" = "-O" ];then
+    # popsc
+    shift
+    mcpop
+    ret=$?
+    if [ $ret -ne 0 ];then
+      exit $ret
+    fi
+    mcpopsc
+  elif [ "$1" = "-x" ];then
+    # pushpopsc
+    shift
+    mcpushx
+  elif [ "$1" = "-c" ];then
+    # cleanup store file
+    echo "echo -n > $_s_file"
+    echo -n > "$_s_file"
   elif [ "$1" = "-S" ];then
     # poponsc
     shift
@@ -535,40 +563,9 @@ _sf_check_args () { # {{{
       mcpoponsc_quit
     fi
     shift
-  elif [ "$1" = "-x" ];then
-    # pushpopsc
+  elif [ "$1" = "-h" ];then
     shift
-    mcpushx
-  elif [ "$1" = "-i" ];then
-    # push
-    shift
-    _sf_push "$*"
-    mccopy2cl "${_s_inputs[0]}"
-  elif [ "$1" = "-I" ];then
-    # pushsc
-    shift
-    touch "$scex"
-    screen -X writebuf
-    _s_noshow=1
-    _sf_push "$(cat "$scex")"
-    mccopy2cl "$(cat "$scex")"
-  elif [ "$1" = "-c" ];then
-    # cleanup store file
-    echo "echo -n > $_s_file"
-    echo -n > "$_s_file"
-  elif [ "$1" = "-o" ];then
-    # pop
-    shift
-    mcpop
-  elif [ "$1" = "-O" ];then
-    # popsc
-    shift
-    mcpop
-    ret=$?
-    if [ $ret -ne 0 ];then
-      exit $ret
-    fi
-    mcpopsc
+    _sf_help
   elif [ "$1" = "-W" ];then
     # mcpopwindow for screen
     shift
